### ISSUE TITLE
Duplicate Outdoor/Outside Temp results

### ISSUE THREAD

**Issue by mww012** [mww012/pyinfinitive#2]
Using version 0.0.3 from pypi, get_stats() returns the following results(formatted to read easier):

`('tempUnit', 'F')
('currentTemp', 71)
('currentHumidity', 52)
('outdoorTemp', 68)
('mode', 'heat')
('stage', 0)
('fanMode', 'auto')
('hold', False)
('holdDurationMins', 0)
('heatSetpoint', 70)
('coolSetpoint', 71)
('targetHumidity', 45)
('rawMode', 0)
('blowerRPM', 0)
('airFlowCFM', 0)
('heatBits', '00000000')
('auxHeat', False)
('tempUnit', '')
('coilTemp', 0)
('outsideTemp', 0)
('stage', 0)`

outdoorTemp and outsideTemp are both returned.  Need to troubleshoot why we're getting both.  @pfiggins may be able to assist.

**Comment by mww012** [comment]
Quick checking shows http://<infinitive_url>/api/heatpump returns outsideTemp where /api/zone/1/config returns outdoorTemp.  This is a discrepancy in the underlying Infinitive API.  If it causes issues we'll need to reconcile the two.  If not, we may just leave it be.

**Comment by pfiggins** [comment]
Yeah, I noticed that when I added it. I also noticed that I received different values between them. The heatpump version seems to be a decimal whereas the one on config is an integer. I figured some people might like one over the other, so I left the config one alone and added the heatpump one even though it would seem to be a duplicate. My feelings won't be hurt if you decide to change that :).

**Comment by mww012** [comment]
No worries.  I'll just leave it then.  I only half fixed the pyinfinitive module when I ran that.  Swapped f-string for str.format() and didn't quite have my syntax right so I was dropping the "heatpump_" before the attributes you created.  Think I've got it all fixed now and will get it pushed to GitHub and pypi as 0.0.4.

**Comment by pfiggins** [comment]
Cool. That's part of the reason I added the prefix on the heatpump dictonary. To make it real clear where they came from, since we have multiple API sources. I didn't notice the prefix was missing. Anywho, glad you got it figured out!

**Comment by mww012** [comment]
I just pushed to pypi as version 0.0.5 (hosed up 0.0.4 and deleted it) and the GitHub repo is updated.  Hopefully I didn't mess anything up for you.

**Comment by pfiggins** [comment]
Perfect. I updated my component via -
REQUIREMENTS = ['pyinfinitive==0.0.5']
and it's working as expected.
